prometheus-operator:
  prometheus:
    additionalServiceMonitors:
      - name: wire-services
        # We copy these labels from the pod onto the collected metrics from that pod
        targetLabels:
          - wireService
        endpoints:
          - path: '/i/metrics'
            port: http
            interval: 3m
            metricRelabelings:
              # Rename 'service' to 'role' to allow sharing of grafana dashboards
              # between k8s and AWS services.
              - sourceLabels: [service]
                targetLabel: role
        namespaceSelector:
          # The namespaces which we can monitor are still limited by the 
          # `prometheus.rbac.roleNamespaces` rules
          any: true
        selector:
          matchExpressions:
            # select any pod with a 'wireService' label
            - key: wireService
              operator: Exists

  prometheusOperator:
    # Don't try to create custom resource types; we prefer to do it manually
    # Otherwise we run into race conditions when installing helm charts
    createCustomResource: false

  grafana:
    adminPassword: "admin"
    ingress:
      enabled: false
    persistence:
      storageClassName: "aws-ebs-retained"
      enabled: true
      accessModes: ["ReadWriteOnce"]
      size: 10Gi

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    # TODO: Chart importing is broken for the time being; should be fixed in 
    # a release soon.
    # REF: https://github.com/helm/charts/issues/12352
    #      https://github.com/helm/charts/pull/12512
    # dashboards:
    #   default:
    #     # grafana can only access files from within its own chart directory
    #     # which we don't have access to here; we can either dump the json
    #     # directly into the values file, or load from a url

    #     brig:
    #       url: https://raw.githubusercontent.com/wireapp/wire-server-deploy/cp/prometheus-operator/charts/wire-server-metrics/dashboards/brig.json
    #     cannon:
    #       url: https://raw.githubusercontent.com/wireapp/wire-server-deploy/cp/prometheus-operator/charts/wire-server-metrics/dashboards/cannon.json
    #     galley:
    #       url: https://raw.githubusercontent.com/wireapp/wire-server-deploy/cp/prometheus-operator/charts/wire-server-metrics/dashboards/galley.json
    #     gundeck:
    #       url: https://raw.githubusercontent.com/wireapp/wire-server-deploy/cp/prometheus-operator/charts/wire-server-metrics/dashboards/gundeck.json

  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "aws-ebs-retained"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "aws-ebs-retained"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  coreDns:
    enabled: false
  kubeDns:
    enabled: true
